name: Pipeline
on: [push]

jobs:
  default-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - name: Bundler
        run: bundle install

      - name: rake
        run: bundle exec rake

      - name: tests
        run: bundle exec rakes test

